apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubeops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubeops
    spec:
      containers:
        - name: busybox
          image: "gcr.io/google_containers/busybox"
          command: ["/bin/sh", "-c","sleep 5; wget -O - ${KUBERNETES_RO_SERVICE_HOST}:${KUBERNETES_RO_SERVICE_PORT}/api/v1/pods/; sleep 10000"]
          ports:
          - containerPort: 8080
          env:
            - name: KUBERNETES_RO_SERVICE_HOST
              value: 127.0.0.1
            - name: KUBERNETES_RO_SERVICE_PORT
              value: "8001"
        - name: kubectl
          image: "gcr.io/google_containers/kubectl:v0.18.0-120-gaeb4ac55ad12b1-dirty"
          args:
            - "proxy"
